medical/urls.py
# -*- coding: UTF-8 -*-

# Copyright (c) 2012-2016 Jose Antonio Chavarría <jachavar@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

__author__ = 'Jose Antonio Chavarría'
__license__ = 'GPLv3'

from django.conf.urls import url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from .views import (
    PatientListView, PatientSearch, PatientCreate, PatientUpdate,
    PatientDelete, PatientRedirectDetail, PatientDetail, PatientRelatives,
    ProblemSearch, ProblemList, ProblemCreate, ProblemUpdate,
    ProblemDetail, ProblemDelete, ProblemConnections,
    HistoryList, HistoryAntecedentsDetail,
    HistoryAntecedentsCreate, HistoryAntecedentsUpdate,
    PatientMedicalReport, ProblemTests, ProblemTestDelete, PatientTests,
)

urlpatterns = [
    url(
        r'^$',
        RedirectView.as_view(
            url=reverse_lazy('patient_list'), permanent=True
        ),
        name='medical_records',
    ),

    url(
        r'^patient/$',
        PatientListView.as_view(),
        name='patient_list',
    ),

    url(
        r'^patient/search/$',
        PatientSearch.as_view(),
        name='patient_search',
    ),

    url(
        r'^patient/add/$',
        PatientCreate.as_view(),
        name='patient_add',
    ),

    url(
        r'^patient/(?P<pk>\d+)/change/$',
        PatientUpdate.as_view(),
        name='patient_change',
    ),

    url(
        r'^patient/(?P<pk>\d+)/delete/$',
        PatientDelete.as_view(),
        name='patient_delete',
    ),

    url(
        r'^patient/(?P<pk>\d+)/$',
        PatientRedirectDetail.as_view(),
        name='patient_redirect_detail',
    ),

    url(
        r'^patient/(?P<pk>\d+)-(?P<slug>[-\w]+)/$',
        PatientDetail.as_view(),
        name='patient_detail',
    ),

    url(
        r'^patient/(?P<pk>\d+)/report/$',
        PatientMedicalReport.as_view(),
        name='patient_medical_report',
    ),

    url(
        r'^patient/(?P<pk>\d+)/relatives/$',
        PatientRelatives.as_view(),
        name='patient_relatives',
    ),

    url(
        r'^patient/(?P<pk>\d+)/tests/$',
        PatientTests.as_view(),
        name='patient_tests',
    ),

    url(
        r'^problem/search/$',
        ProblemSearch.as_view(),
        name='problem_search',
    ),

    url(
        r'^patient/(?P<pk>\d+)/problem/$',
        ProblemList.as_view(),
        name='problem_list',
    ),

    url(
        r'^patient/(?P<pk>\d+)/problem/add/$',
        ProblemCreate.as_view(),
        name='problem_add',
    ),

    url(
        r'^problem/(?P<pk>\d+)/change/$',
        ProblemUpdate.as_view(),
        name='problem_change',
    ),

    url(
        r'^problem/(?P<pk>\d+)/$',
        ProblemDetail.as_view(),
        name='problem_detail',
    ),

    url(
        r'^problem/(?P<pk>\d+)/delete/$',
        ProblemDelete.as_view(),
        name='problem_delete',
    ),

    url(
        r'^problem/(?P<pk>\d+)/connections/$',
        ProblemConnections.as_view(),
        name='problem_connections',
    ),

    url(
        r'^problem/(?P<pk>\d+)/tests/$',
        ProblemTests.as_view(),
        name='problem_tests',
    ),

    url(
        r'^test/(?P<pk>\d+)/delete/$',
        ProblemTestDelete.as_view(),
        name='problem_test_delete',
    ),

    url(
        r'^patient/(?P<pk>\d+)/history/$',
        HistoryList.as_view(),
        name='patient_history',
    ),

    url(
        r'^patient/(?P<pk>\d+)/history/antecedents/$',
        HistoryAntecedentsDetail.as_view(),
        name='patient_history_antecedents',
    ),

    url(
        r'^patient/(?P<pk>\d+)/history/antecedents/add/$',
        HistoryAntecedentsCreate.as_view(),
        name='patient_history_antecedents_add',
    ),

    url(
        r'^patient/(?P<pk>\d+)/history/antecedents/change/$',
        HistoryAntecedentsUpdate.as_view(),
        name='patient_history_antecedents_change',
    ),
]

medical/models/problem.py
# -*- coding: UTF-8 -*-

# Copyright (c) 2012-2016 Jose Antonio Chavarría <jachavar@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

__author__ = 'Jose Antonio Chavarría'
__license__ = 'GPLv3'

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from . import TimeStampedModel


class OpenedManager(models.Manager):
    def get_queryset(self):
        return super(OpenedManager, self).get_queryset().filter(
            closing_date__isnull=True
        )


class ClosedManager(models.Manager):
    def get_queryset(self):
        return super(ClosedManager, self).get_queryset().filter(
            closing_date__isnull=False
        )


@python_2_unicode_compatible
class Problem(TimeStampedModel):
    order_number = models.PositiveSmallIntegerField(
        verbose_name=_('order number')
    )
    closing_date = models.DateField(
        blank=True,
        null=True,
        editable=False,
        verbose_name=_('closing date')
    )

    meeting_place = models.CharField(
        max_length=50,
        null=True,
        blank=True,
        verbose_name=_('meeting place')
    )

    wording = models.TextField(
        verbose_name=_('wording')
    )

    subjetive = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('subjetive')
    )
    objetive = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('objetive')
    )
    appreciation = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('appreciation')
    )
    action_plan = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('action plan')
    )
    prescription = models.TextField(
        null=True,
        blank=True,
        verbose_name=_("doctor's orders")
    )

    patient = models.ForeignKey('Patient')

    doctor = models.ForeignKey(
        'medical.Staff',
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_('attending physician')
    )

    connections = models.ManyToManyField('self', blank=True)

    objects = models.Manager()
    opened = OpenedManager()
    closed = ClosedManager()

    @staticmethod
    def get_last_order_number(patient_id):
        last_order_number = Problem.objects.filter(
            patient_id__exact=patient_id
        ).aggregate(models.Max('order_number'))['order_number__max']
        if not last_order_number:
            last_order_number = 0

        return last_order_number

    def __str__(self):
        return '{}: {}'.format(self.order_number, self.wording)

    class Meta:
        app_label = 'medical'
        db_table = 'problem'
        ordering = ['order_number']
        verbose_name = _('Medical Problem')
        verbose_name_plural = _('Medical Problems')

medical/models/test.py
# -*- coding: UTF-8 -*-

# Copyright (c) 2012-2017 Jose Antonio Chavarría <jachavar@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

__author__ = 'Jose Antonio Chavarría'
__license__ = 'GPLv3'

import os

from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from . import TimeStampedModel


@python_2_unicode_compatible
class Test(TimeStampedModel):
    document_type = models.CharField(
        max_length=128,
        null=True,
        blank=True,
        verbose_name=_('MIME type')
    )
    document = models.FileField(
        upload_to='medical_tests/%Y/%m/%d',
        verbose_name=_('document')
    )

    problem = models.ForeignKey('Problem')

    def filename(self):
        return os.path.basename(self.document.name)

    def __str__(self):
        return str(self.document)

    class Meta:
        app_label = 'medical'


@receiver(pre_delete, sender=Test)
def test_delete(sender, instance, **kwargs):
    instance.document.delete(False)

medical/forms.py
# -*- coding: UTF-8 -*-

# Copyright (c) 2014-2016 Jose Antonio Chavarría <jachavar@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

__author__ = 'Jose Antonio Chavarría'
__license__ = 'GPLv3'

from django import forms
from django.utils.translation import ugettext_lazy as _

from ajax_select.fields import AutoCompleteSelectMultipleField

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit
from crispy_forms.bootstrap import FormActions

from .models import Patient, Problem, Staff, History, Test


class PatientForm(forms.ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                _('Basic data'),
                'first_name',
                'last_name',
                'last_name_optional',
                'gender',
                'doctor_assigned',
                'race',
                'birth_date',
                'birth_place',
                'decease_date',
            ),
            Fieldset(
                _('Administrative data'),
                'address',
                'phone_contact',
                'tin',
                'ssn',
                'health_card_number',
                'insurance_company',
            ),
            Fieldset(
                _('Extra data'),
                'family_situation',
                'labour_situation',
                'education',
            ),
            FormActions(
                Submit('save', _('Save'), css_class='btn-lg'),
            ),
        )
        super(PatientForm, self).__init__(*args, **kwargs)
        self.fields['doctor_assigned'].queryset = Staff.doctors.all()

    class Meta:
        model = Patient
        exclude = ('relatives',)
        widgets = {
            'address': forms.Textarea(attrs={'cols': 30, 'rows': 3}),
            'phone_contact': forms.Textarea(attrs={'cols': 30, 'rows': 3}),
            'family_situation': forms.Textarea(attrs={'cols': 30, 'rows': 3}),
            'labour_situation': forms.Textarea(attrs={'cols': 30, 'rows': 3}),
            'education': forms.Textarea(attrs={'cols': 30, 'rows': 3}),
        }


class PatientSearchForm(forms.Form):
    required_css_class = 'required'

    search_type = forms.ChoiceField(
        label=_('Field'),
        required=True,
        choices=(
            ('last_name', _('Last name')),
            ('first_name', _('First name')),
            ('last_name_optional', _('Last name optional')),
            ('address', _('Address')),
            ('phone_contact', _('Phone contact')),
            ('race', _('Race')),
            ('birth_date', _('Birth date')),
            ('birth_place', _('Birth place')),
            ('decease_date', _('Decease date')),
            ('tin', _('Taxpayer Identification Number (TIN)')),
            ('ssn', _('Social Security Number (SSN)')),
            ('health_card_number', _('Health card number')),
            ('insurance_company', _('Insurance company')),
            # TODO ('collegiate_number', _('Collegiate number')),
        ),
        initial='last_name'
    )

    search_text = forms.CharField(
        label=_('Value'),
        required=False,
        help_text=_('(empty = see all results)')
    )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super(PatientSearchForm, self).__init__(*args, **kwargs)
        self.fields['search_type'].initial = self.request.GET.get(
            'search_type',
            'last_name'
        )
        self.fields['search_text'].initial = self.request.GET.get(
            'search_text',
            ''
        )


class PatientSearchByMedicalProblemForm(forms.Form):
    required_css_class = 'required'

    search_type_problem = forms.ChoiceField(
        label=_('Field'),
        required=True,
        choices=(
            ('wording', _('Wording')),
            ('subjetive', _('Subjetive')),
            ('objetive', _('Objetive')),
            ('appreciation', _('Appreciation')),
            ('action_plan', _('Action Plan')),
            ('prescription', _('Prescription'))
        ),
        initial='wording'
    )

    search_text_problem = forms.CharField(
        label=_('Value'),
        required=False,
        help_text=_('(empty = see all results)')
    )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super(PatientSearchByMedicalProblemForm, self).__init__(*args, **kwargs)
        self.fields['search_type_problem'].initial = self.request.GET.get(
            'search_type_problem', 'wording'
        )
        self.fields['search_text_problem'].initial = self.request.GET.get(
            'search_text_problem', ''
        )


class ProblemForm(forms.ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

    closed = forms.BooleanField(label=_('Closed problem?'), required=False)

    def __init__(self, *args, **kwargs):
        super(ProblemForm, self).__init__(*args, **kwargs)
        self.fields['order_number'].widget.attrs['readonly'] = True
        if self.instance:
            self.fields['closed'].initial = self.instance.closing_date

    class Meta:
        model = Problem
        fields = (
            'order_number', 'doctor', 'wording',
            'meeting_place', 'subjetive', 'objetive', 'appreciation',
            'action_plan', 'prescription', 'closed', 'patient'
        )
        widgets = {
            'patient': forms.HiddenInput(),
        }


class HistoryAntecedentsForm(forms.ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                _('Personal antecedents'),
                'medical_intolerance', 'birth_growth', 'growth_sexuality',
                'feed', 'habits', 'peristaltic_conditions', 'psychological',
                'children_complaint', 'venereal_disease',
                'accident_surgical_operation', 'mental_illness', 'patient',
            ),
            Fieldset(
                _('Family antecedents'),
                'parents_status_health', 'brothers_status_health',
                'spouse_childs_status_health', 'family_illness',
            ),
            FormActions(
                Submit('save', _('Save'), css_class='btn-lg'),
            ),
        )
        super(HistoryAntecedentsForm, self).__init__(*args, **kwargs)

    class Meta:
        model = History
        fields = '__all__'
        widgets = {
            'patient': forms.HiddenInput(),
        }


class PatientRelativesForm(forms.ModelForm):
    relatives = AutoCompleteSelectMultipleField(
        channel='patients',
        required=False,
        help_text='',
        show_help_text=False,
        label=''
    )

    class Meta:
        model = Patient
        fields = ('relatives',)


class ProblemConnectionsForm(forms.ModelForm):
    connections = AutoCompleteSelectMultipleField(
        channel='problems',
        required=False,
        help_text='',
        show_help_text=False,
        label=''
    )

    class Meta:
        model = Problem
        fields = ('connections',)


class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ('document', 'document_type', 'problem')
        widgets = {
            'problem': forms.HiddenInput(),
        }

medical/templates/includes/history_antecedents_detail.html
{% load i18n %}

{% if history %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{% trans 'Personal antecedents' %}</h2>
        </div>
        <div class="panel-body">
            {% if history.medical_intolerance %}
                <p>{% trans 'medical intolerance'|capfirst %}: <strong>{{ history.medical_intolerance }}</strong></p>
            {% endif %}

            {% if history.birth_growth %}
                <p>{% trans 'birth and growth'|capfirst %}: <strong>{{ history.birth_growth }}</strong></p>
            {% endif %}

            {% if history.growth_sexuality %}
                <p>{% trans 'growth and sexuality'|capfirst %}: <strong>{{ history.growth_sexuality }}</strong></p>
            {% endif %}

            {% if history.feed %}
                <p>{% trans 'feed'|capfirst %}: <strong>{{ history.feed }}</strong></p>
            {% endif %}

            {% if history.habits %}
                <p>{% trans 'habits'|capfirst %}: <strong>{{ history.habits }}</strong></p>
            {% endif %}

            {% if history.peristaltic_conditions %}
                <p>{% trans 'peristaltic conditions'|capfirst %}: <strong>{{ history.peristaltic_conditions }}</strong></p>
            {% endif %}

            {% if history.psychological_conditions %}
                <p>{% trans 'psychological conditions'|capfirst %}: <strong>{{ history.psychological_conditions }}</strong></p>
            {% endif %}

            {% if history.children_complaint %}
                <p>{% trans 'children complaint'|capfirst %}: <strong>{{ history.children_complaint }}</strong></p>
            {% endif %}

            {% if history.veneral_disease %}
                <p>{% trans 'veneral disease'|capfirst %}: <strong>{{ history.veneral_disease }}</strong></p>
            {% endif %}

            {% if history.accident_surgical_operation %}
                <p>{% trans 'accidents and surgical operations'|capfirst %}: <strong>{{ history.accident_surgical_operation }}</strong></p>
            {% endif %}

            {% if history.mental_illness %}
                <p>{% trans 'mental illness'|capfirst %}: <strong>{{ history.mental_illness }}</strong></p>
            {% endif %}
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{% trans 'Family antecedents' %}</h2>
        </div>
        <div class="panel-body">
            {% if history.parents_status_health %}
                <p>{% trans 'parents status health'|capfirst %}: <strong>{{ history.parents_status_health }}</strong></p>
            {% endif %}

            {% if history.brothers_status_health %}
                <p>{% trans 'brothers status health'|capfirst %}: <strong>{{ history.brothers_status_health }}</strong></p>
            {% endif %}

            {% if history.spouse_childs_status_health %}
                <p>{% trans 'spouse and childs status health'|capfirst %}: <strong>{{ history.spouse_childs_status_health }}</strong></p>
            {% endif %}

            {% if history.family_illness %}
                <p>{% trans 'family illness'|capfirst %}: <strong>{{ history.family_illness }}</strong></p>
            {% endif %}
        </div>
    </div>
{% endif %}

medical/templates/includes/patient_actions.html
{% load i18n static %}

<ul role="menu" class="patient-actions">
    <li>
        <a href="{% url 'patient_change' patient.id %}" title="{% trans 'Update social data' %}">
            <span class="fa fa-edit"></span> <span class="sr-only">{% trans 'Update' %}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'patient_relatives' patient.id %}" title="{% trans 'Relatives' %}">
            <span class="fa fa-users"></span> <span class="sr-only">{% trans 'Relatives' %}</span>
            <span class="badge">{{ patient.relatives.count }}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'problem_list' patient.id %}" title="{% trans 'Medical problems report' %}">
            <span class="fa fa-user-md"></span> <span class="sr-only">{% trans 'Medical problems report' %}</span>
            <span class="badge">{{ patient.problem_set.count }}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'patient_tests' patient.id %}" title="{% trans 'Medical tests' %}">
            <span class="fa fa-heartbeat"></span> <span class="sr-only">{% trans 'Medical tests' %}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'patient_history' patient.id %}" title="{% trans 'Clinic history' %}">
            <span class="fa fa-ambulance"></span> <span class="sr-only">{% trans 'Clinic history' %}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'patient_medical_report' patient.id %}" title="{% trans 'Print medical report' %}">
            <span class="fa fa-print"></span> <span class="sr-only">{% trans 'Print medical report' %}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'patient_delete' patient.id %}" title="{% trans 'Delete patient' %}" class="btn btn-danger">
            <span class="fa fa-trash-o"></span> <span class="sr-only">{% trans 'Delete patient' %}</span>
        </a>
    </li>
</ul>

medical/templates/includes/patient_detail.html
{% load i18n static %}

{% if patient.doctor_assigned or patient.race or patient.gender or patient.age or patient.birth_place %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{% trans 'Basic data' %}</h2>
        </div>
        <div class="panel-body">
        {% if patient.doctor_assigned %}
            <p>{% trans 'doctor allocated by quota'|capfirst %}: <strong>{{ patient.doctor_assigned }}</strong></p>
        {% endif %}

        {% if patient.race %}
            <p>{% trans 'race'|capfirst %}: <strong>{{ patient.race }}</strong></p>
        {% endif %}

        {% if patient.gender %}
            <p>{% trans 'gender'|capfirst %}: <strong>{{ patient.gender_description }}</strong></p>
        {% endif %}

        {% if patient.birth_place %}
            <p>{% trans 'birth place'|capfirst %}: <strong>{{ patient.birth_place }}</strong></p>
        {% endif %}

        {% if patient.age %}
            <p>{% trans 'Age' %}: <strong>{{ patient.age }}</strong></p>
            <p>{% trans 'birth date'|capfirst %}: <strong>{{ patient.birth_date|date:'Y-m-d' }}</strong></p>
            {% if patient.decease_date %}
                <p class="label label-danger">{% trans 'decease date'|capfirst %}: <strong>{{ patient.decease_date|date:'Y-m-d' }}</strong></p>
            {% endif %}
        {% endif %}
        </div>

        <div class="panel-footer text-center">
            {% include 'includes/patient_actions.html' %}
        </div>
    </div>
{% endif %}

{% if patient.address or patient.phone_contact or patient.tin or patient.ssn or patient.health_card_number or patient.insurance_company %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{% trans 'Administrative data' %}</h2>
        </div>
        <div class="panel-body">
        {% if patient.address %}
            <p>{% trans 'address'|capfirst %}: <strong>{{ patient.address }}</strong></p>
        {% endif %}

        {% if patient.phone_contact %}
            <p>{% trans 'phone contact'|capfirst %}: <strong>{{ patient.phone_contact }}</strong></p>
        {% endif %}

        {% if patient.tin %}
            <p>{% trans 'taxpayer Identification Number (TIN)'|capfirst %}: <strong>{{ patient.tin }}</strong></p>
        {% endif %}

        {% if patient.ssn %}
            <p>{% trans 'social Security Number (SSN)'|capfirst %}: <strong>{{ patient.ssn }}</strong></p>
        {% endif %}

        {% if patient.health_card_number %}
            <p>{% trans 'health card number'|capfirst %}: <strong>{{ patient.health_card_number }}</strong></p>
        {% endif %}

        {% if patient.insurance_company %}
            <p>{% trans 'insurance company'|capfirst %}: <strong>{{ patient.insurance_company }}</strong></p>
        {% endif %}
        </div>
    </div>
{% endif %}

{% if patient.family_situation or patient.labour_situation or patient.education %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{% trans 'Extra data' %}</h2>
        </div>
        <div class="panel-body">
        {% if patient.family_situation %}
            <p>{% trans 'family situation'|capfirst %}: <strong>{{ patient.family_situation }}</strong></p>
        {% endif %}

        {% if patient.labour_situation %}
            <p>{% trans 'labour situation'|capfirst %}: <strong>{{ patient.labour_situation }}</strong></p>
        {% endif %}

        {% if patient.education %}
            <p>{% trans 'education'|capfirst %}: <strong>{{ patient.education }}</strong></p>
        {% endif %}
        </div>
    </div>
{% endif %}

medical/templates/includes/patient_info.html
{% load i18n %}

{% if patient %}
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    {% if forloop %}
                    <div class="col-xs-2 text-right">
                        {{ forloop.counter0|add:pages.current_start_index }}.
                    </div>
                    {% endif %}
                    <div class="col-xs-10">
                        <a href="{% url 'patient_detail' patient.id patient|slugify %}">{{ patient }}</a>
                        {% if patient.gender %}
                            <br />
                            {% trans 'gender'|capfirst %}: {{ patient.gender_description }}
                        {% endif %}
                        {% if patient.age %}
                            <br />
                            {% trans 'Age' %}: {{ patient.age }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="panel-footer text-center">
                {% include 'includes/patient_actions.html' %}
            </div>
        </div>
    </div>
{% endif %}

medical/templates/includes/patient_list.html
{% load i18n %}
{% load el_pagination_tags %}

{% paginate object_list %}
{% get_pages %}

{% for patient in object_list %}
    {% include 'includes/patient_info.html' %}
{% empty %}
    <p class="alert alert-warning">{%trans 'No patients found.' %}</p>
{% endfor %}

{% show_more %}

medical/templates/includes/problem_actions.html
{% load i18n static %}

<ul role="menu" class="patient-actions">
    <li>
        <a href="{% url 'problem_change' problem.id %}" title="{% trans 'Update' %}">
            <span class="fa fa-edit"></span> <span class="sr-only">{% trans 'Update' %}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'problem_tests' problem.id %}" title="{% trans 'Medical tests' %}">
            <span class="fa fa-heartbeat"></span> <span class="sr-only">{% trans 'Medical tests' %}</span>
            <span class="badge">{{ problem.test_set.count }}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'problem_connections' problem.id %}" title="{% trans 'Connections' %}">
            <span class="fa fa-chain"></span> <span class="sr-only">{% trans 'Connections' %}</span>
            <span class="badge">{{ problem.connections.count }}</span>
        </a>
    </li>
    <li>
        <a href="{% url 'problem_delete' problem.id %}" title="{% trans 'Delete medical problem' %}" class="btn btn-danger">
            <span class="fa fa-trash-o"></span> <span class="sr-only">{% trans 'Delete medical problem' %}</span>
        </a>
    </li>
</ul>